plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jizhang.jizhangben'
    compileSdk 34

    defaultConfig {
        applicationId 'com.jizhang.jizhangben'
        minSdk 24
        targetSdk 34
        versionCode 41
        versionName '2.39'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
